# PyTorch from scratch

importing the libraries

In [47]:
import numpy as np
import torch
import pandas as pd

In [48]:
#initialazing a numpy array
a = np.array(1)
#initializing a tensor 
b = torch.tensor(1)
print(a)
print(b)
print(a, b)

1
tensor(1)


In [49]:
type(a), type(b)

(numpy.ndarray, torch.Tensor)

In [50]:
# initializing two arrays
a = np.array([2, 4, 5])
b = np.array([1, 3, 6])
print(a,b)

[2 4 5] [1 3 6]


In [51]:
# addition
print(a+b)

# subtraction
print(b-a)

# multiplication
print(a*b)

# division
print(a/b)

[ 3  7 11]
[-1 -1  1]
[ 2 12 30]
[2.         1.33333333 0.83333333]


In [52]:
# initializing two tensors with PyTorch
a = torch.tensor([2, 3, 2])
b = torch.tensor([1, 3, 8])
print(a,b)

tensor([2, 3, 2]) tensor([1, 3, 8])


In [53]:
# addition
print(a+b)

# subtraction
print(b-a)

# multiplication
print(a*b)

# division
print(a/b)

tensor([ 3,  6, 10])
tensor([-1,  0,  6])
tensor([ 2,  9, 16])
tensor([2, 1, 0])


In [54]:
# matrix of zeros
a = np.zeros((3,3))
print(a)
print(a.shape)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
(3, 3)


In [55]:

# matrix of zeros
a = torch.zeros((3,3))
print(a)
print(a.shape)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.Size([3, 3])


In [56]:
# setting the random seed for numpy
np.random.seed(42)
# matrix of random numbers
a = np.random.randn(3,3)
print(a)
a.shape

[[ 0.49671415 -0.1382643   0.64768854]
 [ 1.52302986 -0.23415337 -0.23413696]
 [ 1.57921282  0.76743473 -0.46947439]]


(3, 3)

In [57]:
# setting the random seed for pytorch
torch.manual_seed(42)
# matrix of random numbers
a = torch.randn(3,3)
print(a)
a.shape

tensor([[ 0.3367,  0.1288,  0.2345],
        [ 0.2303, -1.1229, -0.1863],
        [ 2.2082, -0.6380,  0.4617]])


torch.Size([3, 3])

# Matrix Operations

In [58]:
# setting the random seed for numpy and initializing two matrices
np.random.seed(42)
a = np.random.randn(3,3)
b = np.random.randn(3,3)

In [59]:
# matrix addition
print(np.add(a,b), '\n')

# matrix subtraction
print(np.subtract(a,b), '\n')

# matrix multiplication
print(np.dot(a,b), '\n')

# matrix multiplication
print(np.divide(a,b))

[[ 1.0392742  -0.60168199  0.18195878]
 [ 1.76499213 -2.14743362 -1.95905479]
 [ 1.01692529 -0.24539639 -0.15522705]] 

[[-0.04584589  0.32515339  1.11341829]
 [ 1.28106758  1.67912687  1.49078088]
 [ 2.14150034  1.78026585 -0.78372172]] 

[[-0.12814468 -0.62164688  0.21069439]
 [ 0.90133115 -0.02065676 -0.3790019 ]
 [ 1.30648762 -1.7246546  -2.20677932]] 

[[ 0.9155008   0.29835784 -1.39069607]
 [ 6.29449313  0.12238321  0.13573803]
 [-2.80855031 -0.75771243 -1.49396459]]


In [60]:
# original matrix
print(a, '\n')

# matrix transpose
print(np.transpose(a)) # or a.T

[[ 0.49671415 -0.1382643   0.64768854]
 [ 1.52302986 -0.23415337 -0.23413696]
 [ 1.57921282  0.76743473 -0.46947439]] 

[[ 0.49671415  1.52302986  1.57921282]
 [-0.1382643  -0.23415337  0.76743473]
 [ 0.64768854 -0.23413696 -0.46947439]]


In [61]:
# matrix addition
a = torch.randn(3, 3)
b = torch.randn(3, 3)
print(torch.add(a,b), '\n')

# matrix subtraction
print(torch.sub(a,b), '\n')

# matrix multiplication
print(torch.mm(a,b), '\n')

# matrix division
print(torch.div(a,b))

tensor([[-0.4985, -0.2157,  2.1619],
        [ 1.7966, -2.0176, -0.1940],
        [ 1.2395,  1.3783,  1.3399]]) 

tensor([[ 1.0332,  1.2855, -0.5432],
        [ 0.4240, -1.3620, -1.7839],
        [ 0.6765,  1.2660,  0.2945]]) 

tensor([[ 0.3902, -0.3305,  1.2099],
        [-2.2885, -0.3351, -0.3586],
        [ 0.4038, -1.1065,  2.7739]]) 

tensor([[-0.3491, -0.7126,  0.5984],
        [ 1.6177,  5.1556, -1.2440],
        [ 3.4029, 23.5408,  1.5634]])


In [62]:
#original matrix
print(a, '\n')

# matrix transpose
torch.t(a)


tensor([[ 0.2674,  0.5349,  0.8094],
        [ 1.1103, -1.6898, -0.9890],
        [ 0.9580,  1.3221,  0.8172]]) 



tensor([[ 0.2674,  1.1103,  0.9580],
        [ 0.5349, -1.6898,  1.3221],
        [ 0.8094, -0.9890,  0.8172]])

# Concatenating Tensors

#initializing two tensors
a = torch.tensor([[1, 2], [3, 4]])

b = torch.tensor([[5, 6],[7, 8]])

print(a, '\n')

b

In [64]:
# concatenating vertically

torch.cat((a, b))

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [65]:
# concatenating horizontally

torch.cat((a, b), dim = 1)

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])

# Reshaping Tensors

In [73]:
# reshaping tensor

a = torch.randn(2, 4)
print(a)
print(a.shape, '\n')

b = a.reshape(1, 8)
print(b)
print(b.shape, '\n')

tensor([[-0.5706,  1.5980,  0.1115, -0.0392],
        [ 1.4112, -0.6556,  0.8576, -1.6270]])
torch.Size([2, 4]) 

tensor([[-0.5706,  1.5980,  0.1115, -0.0392,  1.4112, -0.6556,  0.8576, -1.6270]])
torch.Size([1, 8]) 



In [74]:
# initializing a tensor

a = torch.ones((2,2), requires_grad=True)

a

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [77]:
b = a + 5
b

tensor([[6., 6.],
        [6., 6.]], grad_fn=<AddBackward0>)

In [79]:
c = torch.mean(b)

c.shape

torch.Size([])